CREATE TABLE users (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    local_id BIGINT NOT NULL,
    device_id VARCHAR(255) NOT NULL,
    restaurant_id BIGINT NOT NULL,
    updated_at BIGINT NOT NULL,
    is_deleted BOOLEAN NOT NULL DEFAULT FALSE,
    server_updated_at BIGINT NOT NULL DEFAULT 0,
    created_at BIGINT NOT NULL,
    name VARCHAR(255) NOT NULL,
    email VARCHAR(255),
    login_id VARCHAR(255) NOT NULL,
    google_email VARCHAR(255),
    auth_provider VARCHAR(20) NOT NULL,
    password_hash VARCHAR(255),
    whatsapp_number VARCHAR(255),
    role VARCHAR(50) NOT NULL DEFAULT 'OWNER',
    is_active BOOLEAN NOT NULL DEFAULT TRUE,
    version BIGINT NOT NULL DEFAULT 0,
    phone_number VARCHAR(255),
    token_invalidated_at BIGINT,
    CONSTRAINT chk_users_auth_provider CHECK (auth_provider IN ('PHONE', 'GOOGLE'))
);

CREATE TABLE restaurantprofiles (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    local_id BIGINT NOT NULL,
    device_id VARCHAR(255) NOT NULL,
    restaurant_id BIGINT NOT NULL,
    updated_at BIGINT NOT NULL,
    is_deleted BOOLEAN NOT NULL DEFAULT FALSE,
    server_updated_at BIGINT NOT NULL DEFAULT 0,
    created_at BIGINT NOT NULL,
    shop_name VARCHAR(255),
    shop_address VARCHAR(255),
    whatsapp_number VARCHAR(255),
    email VARCHAR(255),
    logo_path VARCHAR(255),
    fssai_number VARCHAR(255),
    email_invoice_consent BOOLEAN,
    country VARCHAR(100),
    gst_enabled BOOLEAN,
    gstin VARCHAR(255),
    is_tax_inclusive BOOLEAN,
    gst_percentage NUMERIC(12,2),
    custom_tax_name VARCHAR(255),
    custom_tax_number VARCHAR(255),
    custom_tax_percentage NUMERIC(12,2),
    currency VARCHAR(50),
    upi_enabled BOOLEAN,
    upi_qr_path VARCHAR(255),
    upi_handle VARCHAR(255),
    upi_mobile VARCHAR(255),
    cash_enabled BOOLEAN,
    pos_enabled BOOLEAN,
    zomato_enabled BOOLEAN,
    swiggy_enabled BOOLEAN,
    own_website_enabled BOOLEAN,
    printer_enabled BOOLEAN,
    printer_name VARCHAR(255),
    printer_mac VARCHAR(255),
    paper_size VARCHAR(50),
    auto_print_on_success BOOLEAN,
    include_logo_in_print BOOLEAN,
    print_customer_whatsapp BOOLEAN,
    daily_order_counter BIGINT,
    lifetime_order_counter BIGINT,
    last_reset_date VARCHAR(50),
    session_timeout_minutes INTEGER,
    timezone VARCHAR(100) DEFAULT 'Asia/Kolkata',
    review_url VARCHAR(500),
    show_branding BOOLEAN DEFAULT TRUE,
    mask_customer_phone BOOLEAN DEFAULT TRUE,
    version BIGINT NOT NULL DEFAULT 0,
    last_reset_date_proper DATE,
    CONSTRAINT restaurantprofiles_restaurant_id_device_id_local_id_key
        UNIQUE (restaurant_id, device_id, local_id)
);

CREATE TABLE categories (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    local_id BIGINT NOT NULL,
    device_id VARCHAR(255) NOT NULL,
    restaurant_id BIGINT NOT NULL,
    updated_at BIGINT NOT NULL,
    is_deleted BOOLEAN NOT NULL DEFAULT FALSE,
    server_updated_at BIGINT NOT NULL DEFAULT 0,
    created_at BIGINT NOT NULL,
    name VARCHAR(255) NOT NULL,
    is_veg BOOLEAN NOT NULL DEFAULT FALSE,
    sort_order INTEGER,
    is_active BOOLEAN NOT NULL DEFAULT TRUE,
    version BIGINT NOT NULL DEFAULT 0
);

CREATE TABLE menuitems (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    local_id BIGINT NOT NULL,
    device_id VARCHAR(255) NOT NULL,
    restaurant_id BIGINT NOT NULL,
    updated_at BIGINT NOT NULL,
    is_deleted BOOLEAN NOT NULL DEFAULT FALSE,
    server_updated_at BIGINT NOT NULL DEFAULT 0,
    created_at BIGINT NOT NULL,
    category_id BIGINT NOT NULL,
    server_category_id BIGINT,
    name VARCHAR(255) NOT NULL,
    base_price NUMERIC(12,2) NOT NULL,
    food_type VARCHAR(50),
    description TEXT,
    is_available BOOLEAN NOT NULL DEFAULT TRUE,
    current_stock NUMERIC(12,4),
    low_stock_threshold NUMERIC(12,4),
    barcode VARCHAR(255),
    version BIGINT NOT NULL DEFAULT 0,
    CONSTRAINT chk_menuitems_price CHECK (base_price >= 0)
);

CREATE TABLE itemvariants (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    local_id BIGINT NOT NULL,
    device_id VARCHAR(255) NOT NULL,
    restaurant_id BIGINT NOT NULL,
    updated_at BIGINT NOT NULL,
    is_deleted BOOLEAN NOT NULL DEFAULT FALSE,
    server_updated_at BIGINT NOT NULL DEFAULT 0,
    created_at BIGINT NOT NULL,
    menu_item_id BIGINT NOT NULL,
    server_menu_item_id BIGINT,
    variant_name VARCHAR(255) NOT NULL,
    price NUMERIC(12,2) NOT NULL,
    is_available BOOLEAN NOT NULL DEFAULT TRUE,
    sort_order INTEGER,
    current_stock NUMERIC(12,4),
    low_stock_threshold NUMERIC(12,4),
    version BIGINT NOT NULL DEFAULT 0,
    CONSTRAINT chk_itemvariants_price CHECK (price >= 0)
);

CREATE TABLE bills (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    local_id BIGINT NOT NULL,
    device_id VARCHAR(255) NOT NULL,
    restaurant_id BIGINT NOT NULL,
    updated_at BIGINT NOT NULL,
    is_deleted BOOLEAN NOT NULL DEFAULT FALSE,
    server_updated_at BIGINT NOT NULL DEFAULT 0,
    created_at BIGINT NOT NULL,
    daily_order_id BIGINT NOT NULL,
    daily_order_display VARCHAR(255),
    lifetime_order_id BIGINT NOT NULL,
    order_type VARCHAR(100) NOT NULL,
    customer_name VARCHAR(255),
    customer_whatsapp VARCHAR(255),
    subtotal NUMERIC(12,2) NOT NULL,
    gst_percentage NUMERIC(12,2),
    cgst_amount NUMERIC(12,2),
    sgst_amount NUMERIC(12,2),
    custom_tax_amount NUMERIC(12,2),
    total_amount NUMERIC(12,2) NOT NULL,
    payment_mode VARCHAR(100) NOT NULL,
    part_amount_1 NUMERIC(12,2),
    part_amount_2 NUMERIC(12,2),
    payment_status VARCHAR(100) NOT NULL,
    order_status VARCHAR(100) NOT NULL,
    created_by BIGINT,
    paid_at BIGINT,
    last_reset_date VARCHAR(50) NOT NULL,
    version BIGINT NOT NULL DEFAULT 0,
    cancel_reason VARCHAR(500) NOT NULL DEFAULT '',
    CONSTRAINT bills_restaurant_id_device_id_local_id_key
        UNIQUE (restaurant_id, device_id, local_id),
    CONSTRAINT chk_bills_subtotal CHECK (subtotal >= 0),
    CONSTRAINT chk_bills_total CHECK (total_amount >= 0)
);

CREATE TABLE bill_items (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    local_id BIGINT NOT NULL,
    device_id VARCHAR(255) NOT NULL,
    restaurant_id BIGINT NOT NULL,
    updated_at BIGINT NOT NULL,
    is_deleted BOOLEAN NOT NULL DEFAULT FALSE,
    server_updated_at BIGINT NOT NULL DEFAULT 0,
    created_at BIGINT NOT NULL,
    bill_id BIGINT NOT NULL,
    server_bill_id BIGINT,
    menu_item_id BIGINT NOT NULL,
    server_menu_item_id BIGINT,
    item_name VARCHAR(255) NOT NULL,
    variant_id BIGINT,
    server_variant_id BIGINT,
    variant_name VARCHAR(255),
    price NUMERIC(12,2) NOT NULL,
    quantity INTEGER NOT NULL,
    item_total NUMERIC(12,2) NOT NULL,
    special_instruction VARCHAR(500),
    version BIGINT NOT NULL DEFAULT 0,
    CONSTRAINT bill_items_restaurant_id_device_id_local_id_key
        UNIQUE (restaurant_id, device_id, local_id),
    CONSTRAINT chk_bill_items_price CHECK (price >= 0),
    CONSTRAINT chk_bill_items_quantity CHECK (quantity > 0),
    CONSTRAINT chk_bill_items_total CHECK (item_total >= 0)
);

CREATE TABLE bill_payments (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    local_id BIGINT NOT NULL,
    device_id VARCHAR(255) NOT NULL,
    restaurant_id BIGINT NOT NULL,
    updated_at BIGINT NOT NULL,
    is_deleted BOOLEAN NOT NULL DEFAULT FALSE,
    server_updated_at BIGINT NOT NULL DEFAULT 0,
    created_at BIGINT NOT NULL,
    bill_id BIGINT NOT NULL,
    server_bill_id BIGINT,
    payment_mode VARCHAR(100) NOT NULL,
    amount NUMERIC(12,2) NOT NULL,
    version BIGINT NOT NULL DEFAULT 0,
    CONSTRAINT bill_payments_restaurant_id_device_id_local_id_key
        UNIQUE (restaurant_id, device_id, local_id),
    CONSTRAINT chk_bill_payment_mode CHECK (
        payment_mode IN ('cash', 'upi', 'pos', 'part_cash_upi', 'part_cash_pos', 'part_upi_pos', 'zomato', 'swiggy', 'own_website')
    ),
    CONSTRAINT chk_bill_payments_amount CHECK (amount >= 0)
);

CREATE TABLE stock_logs (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    local_id BIGINT NOT NULL,
    device_id VARCHAR(255) NOT NULL,
    restaurant_id BIGINT NOT NULL,
    updated_at BIGINT NOT NULL,
    is_deleted BOOLEAN NOT NULL DEFAULT FALSE,
    server_updated_at BIGINT NOT NULL DEFAULT 0,
    created_at BIGINT NOT NULL,
    menu_item_id BIGINT NOT NULL,
    server_menu_item_id BIGINT,
    variant_id BIGINT,
    server_variant_id BIGINT,
    delta NUMERIC(12,4) NOT NULL,
    reason VARCHAR(255) NOT NULL,
    version BIGINT NOT NULL DEFAULT 0
);

CREATE TABLE menu_extraction_jobs (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    restaurant_id BIGINT,
    file_path VARCHAR(500),
    status VARCHAR(50),
    extracted_data_json TEXT,
    created_at TIMESTAMP,
    completed_at TIMESTAMP,
    error_message TEXT
);

CREATE TABLE otp_requests (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    challenge_key VARCHAR(255) NOT NULL,
    phone_number VARCHAR(20) NOT NULL,
    otp VARCHAR(60) NOT NULL,
    expires_at BIGINT NOT NULL,
    attempts INTEGER NOT NULL DEFAULT 0,
    created_at BIGINT NOT NULL
);

CREATE TABLE token_blocklist (
    jti VARCHAR(64) PRIMARY KEY,
    expires_at BIGINT NOT NULL,
    revoked_at BIGINT NOT NULL
);

CREATE UNIQUE INDEX uk_users_email ON users(email);
CREATE UNIQUE INDEX idx_users_phone_number ON users(phone_number) WHERE phone_number IS NOT NULL;
CREATE INDEX idx_users_device ON users(restaurant_id, device_id, local_id);
CREATE INDEX idx_users_google_email ON users(google_email);
CREATE INDEX idx_users_restaurant_active ON users(restaurant_id, is_active);
CREATE INDEX idx_users_tenant_server_updated ON users(restaurant_id, server_updated_at);
CREATE INDEX idx_users_tenant_updated ON users(restaurant_id, updated_at);
CREATE INDEX idx_users_whatsapp_number ON users(whatsapp_number);

CREATE INDEX idx_restaurantprofiles_device ON restaurantprofiles(restaurant_id, device_id, local_id);
CREATE INDEX idx_restaurantprofiles_tenant_updated ON restaurantprofiles(restaurant_id, updated_at);
CREATE INDEX idx_restaurantprofiles_whatsapp_number ON restaurantprofiles(whatsapp_number);

CREATE INDEX idx_categories_device ON categories(restaurant_id, device_id, local_id);
CREATE INDEX idx_categories_tenant_deleted ON categories(restaurant_id, is_deleted);
CREATE INDEX idx_categories_tenant_server_updated ON categories(restaurant_id, server_updated_at);
CREATE INDEX idx_categories_tenant_updated ON categories(restaurant_id, updated_at);

CREATE INDEX idx_menuitems_device ON menuitems(restaurant_id, device_id, local_id);
CREATE INDEX idx_menu_items_category ON menuitems(restaurant_id, category_id);
CREATE INDEX idx_menuitems_server_category ON menuitems(server_category_id) WHERE server_category_id IS NOT NULL;
CREATE INDEX idx_menuitems_tenant_deleted ON menuitems(restaurant_id, is_deleted);
CREATE INDEX idx_menuitems_tenant_server_updated ON menuitems(restaurant_id, server_updated_at);
CREATE INDEX idx_menuitems_tenant_updated ON menuitems(restaurant_id, updated_at);

CREATE INDEX idx_itemvariants_device ON itemvariants(restaurant_id, device_id, local_id);
CREATE INDEX idx_itemvariants_server_menuitem ON itemvariants(server_menu_item_id) WHERE server_menu_item_id IS NOT NULL;
CREATE INDEX idx_itemvariants_tenant_deleted ON itemvariants(restaurant_id, is_deleted);
CREATE INDEX idx_itemvariants_tenant_server_updated ON itemvariants(restaurant_id, server_updated_at);
CREATE INDEX idx_itemvariants_tenant_updated ON itemvariants(restaurant_id, updated_at);

CREATE INDEX idx_bills_device ON bills(restaurant_id, device_id, local_id);
CREATE INDEX idx_bills_tenant_created ON bills(restaurant_id, created_at);
CREATE INDEX idx_bills_tenant_date ON bills(restaurant_id, updated_at);
CREATE INDEX idx_bills_tenant_deleted ON bills(restaurant_id, is_deleted);
CREATE INDEX idx_bills_tenant_payment_status ON bills(restaurant_id, payment_status);
CREATE INDEX idx_bills_tenant_server_updated ON bills(restaurant_id, server_updated_at);
CREATE INDEX idx_bills_tenant_status ON bills(restaurant_id, order_status);
CREATE INDEX idx_bills_tenant_updated ON bills(restaurant_id, updated_at);

CREATE INDEX idx_bill_items_bill_id ON bill_items(bill_id);
CREATE INDEX idx_bill_items_device ON bill_items(restaurant_id, device_id, local_id);
CREATE INDEX idx_bill_items_server_bill ON bill_items(server_bill_id) WHERE server_bill_id IS NOT NULL;
CREATE INDEX idx_bill_items_server_menuitem ON bill_items(server_menu_item_id) WHERE server_menu_item_id IS NOT NULL;
CREATE INDEX idx_bill_items_server_variant ON bill_items(server_variant_id) WHERE server_variant_id IS NOT NULL;
CREATE INDEX idx_bill_items_tenant_deleted ON bill_items(restaurant_id, is_deleted);
CREATE INDEX idx_bill_items_tenant_server_updated ON bill_items(restaurant_id, server_updated_at);
CREATE INDEX idx_bill_items_tenant_updated ON bill_items(restaurant_id, updated_at);

CREATE INDEX idx_bill_payments_bill_id ON bill_payments(bill_id);
CREATE INDEX idx_bill_payments_device ON bill_payments(restaurant_id, device_id, local_id);
CREATE INDEX idx_bill_payments_server_bill ON bill_payments(server_bill_id) WHERE server_bill_id IS NOT NULL;
CREATE INDEX idx_bill_payments_tenant_deleted ON bill_payments(restaurant_id, is_deleted);
CREATE INDEX idx_bill_payments_tenant_server_updated ON bill_payments(restaurant_id, server_updated_at);
CREATE INDEX idx_bill_payments_tenant_updated ON bill_payments(restaurant_id, updated_at);

CREATE INDEX idx_stock_logs_device ON stock_logs(restaurant_id, device_id, local_id);
CREATE INDEX idx_stock_logs_server_menuitem ON stock_logs(server_menu_item_id) WHERE server_menu_item_id IS NOT NULL;
CREATE INDEX idx_stock_logs_server_variant ON stock_logs(server_variant_id) WHERE server_variant_id IS NOT NULL;
CREATE INDEX idx_stock_logs_tenant_deleted ON stock_logs(restaurant_id, is_deleted);
CREATE INDEX idx_stock_logs_tenant_server_updated ON stock_logs(restaurant_id, server_updated_at);
CREATE INDEX idx_stock_logs_tenant_updated ON stock_logs(restaurant_id, updated_at);

CREATE INDEX idx_menu_extraction_jobs_restaurant ON menu_extraction_jobs(restaurant_id);
CREATE INDEX idx_menu_extraction_jobs_status ON menu_extraction_jobs(status);

CREATE UNIQUE INDEX ux_otp_requests_challenge_key ON otp_requests(challenge_key);
CREATE INDEX idx_otp_requests_expires_at ON otp_requests(expires_at);
CREATE INDEX idx_otp_requests_phone ON otp_requests(phone_number);

CREATE INDEX idx_token_blocklist_expires ON token_blocklist(expires_at);

ALTER TABLE menuitems
    ADD CONSTRAINT fk_menuitems_category
    FOREIGN KEY (server_category_id) REFERENCES categories(id)
    ON DELETE SET NULL DEFERRABLE INITIALLY DEFERRED;

ALTER TABLE itemvariants
    ADD CONSTRAINT fk_itemvariants_menuitem
    FOREIGN KEY (server_menu_item_id) REFERENCES menuitems(id)
    ON DELETE SET NULL DEFERRABLE INITIALLY DEFERRED;

ALTER TABLE bill_items
    ADD CONSTRAINT fk_bill_items_bill
    FOREIGN KEY (bill_id) REFERENCES bills(id)
    ON DELETE CASCADE;

ALTER TABLE bill_items
    ADD CONSTRAINT fk_bill_items_menuitem
    FOREIGN KEY (server_menu_item_id) REFERENCES menuitems(id)
    ON DELETE SET NULL DEFERRABLE INITIALLY DEFERRED;

ALTER TABLE bill_items
    ADD CONSTRAINT fk_bill_items_variant
    FOREIGN KEY (server_variant_id) REFERENCES itemvariants(id)
    ON DELETE SET NULL DEFERRABLE INITIALLY DEFERRED;

ALTER TABLE bill_payments
    ADD CONSTRAINT fk_bill_payments_bill
    FOREIGN KEY (bill_id) REFERENCES bills(id)
    ON DELETE CASCADE;

ALTER TABLE stock_logs
    ADD CONSTRAINT fk_stock_logs_menuitem
    FOREIGN KEY (server_menu_item_id) REFERENCES menuitems(id)
    ON DELETE SET NULL DEFERRABLE INITIALLY DEFERRED;

ALTER TABLE stock_logs
    ADD CONSTRAINT fk_stock_logs_variant
    FOREIGN KEY (server_variant_id) REFERENCES itemvariants(id)
    ON DELETE SET NULL DEFERRABLE INITIALLY DEFERRED;
