CREATE TABLE IF NOT EXISTS users (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    local_id BIGINT NOT NULL,
    device_id VARCHAR(255) NOT NULL,
    restaurant_id BIGINT NOT NULL,
    updated_at BIGINT NOT NULL,
    is_deleted BOOLEAN NOT NULL DEFAULT FALSE,
    server_updated_at BIGINT NOT NULL DEFAULT 0,
    created_at BIGINT NOT NULL,
    name VARCHAR(255) NOT NULL,
    email VARCHAR(255) NOT NULL,
    login_id VARCHAR(255),
    google_email VARCHAR(255),
    auth_provider VARCHAR(20),
    password_hash VARCHAR(255),
    whatsapp_number VARCHAR(255),
    role VARCHAR(50) NOT NULL DEFAULT 'OWNER',
    is_active BOOLEAN NOT NULL DEFAULT TRUE
);

CREATE UNIQUE INDEX IF NOT EXISTS uk_users_email ON users(email);
CREATE UNIQUE INDEX IF NOT EXISTS ux_users_login_id ON users(login_id) WHERE login_id IS NOT NULL;
CREATE INDEX IF NOT EXISTS idx_users_tenant_updated ON users(restaurant_id, updated_at);
CREATE INDEX IF NOT EXISTS idx_users_device ON users(restaurant_id, device_id, local_id);
CREATE INDEX IF NOT EXISTS idx_users_whatsapp_number ON users(whatsapp_number);
CREATE INDEX IF NOT EXISTS idx_users_google_email ON users(google_email);

CREATE TABLE IF NOT EXISTS restaurantprofiles (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    local_id BIGINT NOT NULL,
    device_id VARCHAR(255) NOT NULL,
    restaurant_id BIGINT NOT NULL,
    updated_at BIGINT NOT NULL,
    is_deleted BOOLEAN NOT NULL DEFAULT FALSE,
    server_updated_at BIGINT NOT NULL DEFAULT 0,
    created_at BIGINT NOT NULL,
    shop_name VARCHAR(255),
    shop_address VARCHAR(255),
    whatsapp_number VARCHAR(255),
    email VARCHAR(255),
    logo_path VARCHAR(255),
    fssai_number VARCHAR(255),
    email_invoice_consent BOOLEAN,
    country VARCHAR(100),
    gst_enabled BOOLEAN,
    gstin VARCHAR(255),
    is_tax_inclusive BOOLEAN,
    gst_percentage NUMERIC(12,2),
    custom_tax_name VARCHAR(255),
    custom_tax_number VARCHAR(255),
    custom_tax_percentage NUMERIC(12,2),
    currency VARCHAR(50),
    upi_enabled BOOLEAN,
    upi_qr_path VARCHAR(255),
    upi_handle VARCHAR(255),
    upi_mobile VARCHAR(255),
    cash_enabled BOOLEAN,
    pos_enabled BOOLEAN,
    zomato_enabled BOOLEAN,
    swiggy_enabled BOOLEAN,
    own_website_enabled BOOLEAN,
    printer_enabled BOOLEAN,
    printer_name VARCHAR(255),
    printer_mac VARCHAR(255),
    paper_size VARCHAR(50),
    auto_print_on_success BOOLEAN,
    include_logo_in_print BOOLEAN,
    print_customer_whatsapp BOOLEAN,
    daily_order_counter BIGINT,
    lifetime_order_counter BIGINT,
    last_reset_date VARCHAR(50),
    session_timeout_minutes INTEGER,
    timezone VARCHAR(100) DEFAULT 'Asia/Kolkata',
    review_url VARCHAR(500),
    show_branding BOOLEAN DEFAULT TRUE,
    mask_customer_phone BOOLEAN DEFAULT TRUE,
    CONSTRAINT restaurantprofiles_restaurant_id_device_id_local_id_key
        UNIQUE (restaurant_id, device_id, local_id)
);

CREATE INDEX IF NOT EXISTS idx_restaurantprofiles_tenant_updated ON restaurantprofiles(restaurant_id, updated_at);
CREATE INDEX IF NOT EXISTS idx_restaurantprofiles_device ON restaurantprofiles(restaurant_id, device_id, local_id);
CREATE INDEX IF NOT EXISTS idx_restaurantprofiles_whatsapp_number ON restaurantprofiles(whatsapp_number);

CREATE TABLE IF NOT EXISTS categories (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    local_id BIGINT NOT NULL,
    device_id VARCHAR(255) NOT NULL,
    restaurant_id BIGINT NOT NULL,
    updated_at BIGINT NOT NULL,
    is_deleted BOOLEAN NOT NULL DEFAULT FALSE,
    server_updated_at BIGINT NOT NULL DEFAULT 0,
    created_at BIGINT NOT NULL,
    name VARCHAR(255) NOT NULL,
    is_veg BOOLEAN NOT NULL DEFAULT FALSE,
    sort_order INTEGER,
    is_active BOOLEAN NOT NULL DEFAULT TRUE
);

CREATE INDEX IF NOT EXISTS idx_categories_tenant_updated ON categories(restaurant_id, updated_at);
CREATE INDEX IF NOT EXISTS idx_categories_device ON categories(restaurant_id, device_id, local_id);

CREATE TABLE IF NOT EXISTS menuitems (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    local_id BIGINT NOT NULL,
    device_id VARCHAR(255) NOT NULL,
    restaurant_id BIGINT NOT NULL,
    updated_at BIGINT NOT NULL,
    is_deleted BOOLEAN NOT NULL DEFAULT FALSE,
    server_updated_at BIGINT NOT NULL DEFAULT 0,
    created_at BIGINT NOT NULL,
    category_id BIGINT NOT NULL,
    server_category_id BIGINT,
    name VARCHAR(255) NOT NULL,
    base_price NUMERIC(12,2) NOT NULL,
    food_type VARCHAR(50),
    description TEXT,
    is_available BOOLEAN NOT NULL DEFAULT TRUE,
    current_stock NUMERIC(12,4),
    low_stock_threshold NUMERIC(12,4)
);

CREATE INDEX IF NOT EXISTS idx_menuitems_tenant_updated ON menuitems(restaurant_id, updated_at);
CREATE INDEX IF NOT EXISTS idx_menuitems_device ON menuitems(restaurant_id, device_id, local_id);

CREATE TABLE IF NOT EXISTS itemvariants (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    local_id BIGINT NOT NULL,
    device_id VARCHAR(255) NOT NULL,
    restaurant_id BIGINT NOT NULL,
    updated_at BIGINT NOT NULL,
    is_deleted BOOLEAN NOT NULL DEFAULT FALSE,
    server_updated_at BIGINT NOT NULL DEFAULT 0,
    created_at BIGINT NOT NULL,
    menu_item_id BIGINT NOT NULL,
    server_menu_item_id BIGINT,
    variant_name VARCHAR(255) NOT NULL,
    price NUMERIC(12,2) NOT NULL,
    is_available BOOLEAN NOT NULL DEFAULT TRUE,
    sort_order INTEGER,
    current_stock NUMERIC(12,4),
    low_stock_threshold NUMERIC(12,4)
);

CREATE INDEX IF NOT EXISTS idx_itemvariants_tenant_updated ON itemvariants(restaurant_id, updated_at);
CREATE INDEX IF NOT EXISTS idx_itemvariants_device ON itemvariants(restaurant_id, device_id, local_id);

CREATE TABLE IF NOT EXISTS bills (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    local_id BIGINT NOT NULL,
    device_id VARCHAR(255) NOT NULL,
    restaurant_id BIGINT NOT NULL,
    updated_at BIGINT NOT NULL,
    is_deleted BOOLEAN NOT NULL DEFAULT FALSE,
    server_updated_at BIGINT NOT NULL DEFAULT 0,
    created_at BIGINT NOT NULL,
    daily_order_id BIGINT NOT NULL,
    daily_order_display VARCHAR(255),
    lifetime_order_id BIGINT NOT NULL,
    order_type VARCHAR(100) NOT NULL,
    customer_name VARCHAR(255),
    customer_whatsapp VARCHAR(255),
    subtotal NUMERIC(12,2) NOT NULL,
    gst_percentage NUMERIC(12,2),
    cgst_amount NUMERIC(12,2),
    sgst_amount NUMERIC(12,2),
    custom_tax_amount NUMERIC(12,2),
    total_amount NUMERIC(12,2) NOT NULL,
    payment_mode VARCHAR(100) NOT NULL,
    part_amount_1 NUMERIC(12,2),
    part_amount_2 NUMERIC(12,2),
    payment_status VARCHAR(100) NOT NULL,
    order_status VARCHAR(100) NOT NULL,
    created_by BIGINT,
    paid_at BIGINT,
    last_reset_date VARCHAR(50) NOT NULL
);

CREATE INDEX IF NOT EXISTS idx_bills_tenant_updated ON bills(restaurant_id, updated_at);
CREATE INDEX IF NOT EXISTS idx_bills_device ON bills(restaurant_id, device_id, local_id);

CREATE TABLE IF NOT EXISTS bill_items (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    local_id BIGINT NOT NULL,
    device_id VARCHAR(255) NOT NULL,
    restaurant_id BIGINT NOT NULL,
    updated_at BIGINT NOT NULL,
    is_deleted BOOLEAN NOT NULL DEFAULT FALSE,
    server_updated_at BIGINT NOT NULL DEFAULT 0,
    created_at BIGINT NOT NULL,
    bill_id BIGINT NOT NULL,
    server_bill_id BIGINT,
    menu_item_id BIGINT NOT NULL,
    server_menu_item_id BIGINT,
    item_name VARCHAR(255) NOT NULL,
    variant_id BIGINT,
    server_variant_id BIGINT,
    variant_name VARCHAR(255),
    price NUMERIC(12,2) NOT NULL,
    quantity INTEGER NOT NULL,
    item_total NUMERIC(12,2) NOT NULL,
    special_instruction VARCHAR(500)
);

CREATE INDEX IF NOT EXISTS idx_bill_items_tenant_updated ON bill_items(restaurant_id, updated_at);
CREATE INDEX IF NOT EXISTS idx_bill_items_device ON bill_items(restaurant_id, device_id, local_id);

CREATE TABLE IF NOT EXISTS bill_payments (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    local_id BIGINT NOT NULL,
    device_id VARCHAR(255) NOT NULL,
    restaurant_id BIGINT NOT NULL,
    updated_at BIGINT NOT NULL,
    is_deleted BOOLEAN NOT NULL DEFAULT FALSE,
    server_updated_at BIGINT NOT NULL DEFAULT 0,
    created_at BIGINT NOT NULL,
    bill_id BIGINT NOT NULL,
    server_bill_id BIGINT,
    payment_mode VARCHAR(100) NOT NULL,
    amount NUMERIC(12,2) NOT NULL
);

CREATE INDEX IF NOT EXISTS idx_bill_payments_tenant_updated ON bill_payments(restaurant_id, updated_at);
CREATE INDEX IF NOT EXISTS idx_bill_payments_device ON bill_payments(restaurant_id, device_id, local_id);

CREATE TABLE IF NOT EXISTS stock_logs (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    local_id BIGINT NOT NULL,
    device_id VARCHAR(255) NOT NULL,
    restaurant_id BIGINT NOT NULL,
    updated_at BIGINT NOT NULL,
    is_deleted BOOLEAN NOT NULL DEFAULT FALSE,
    server_updated_at BIGINT NOT NULL DEFAULT 0,
    created_at BIGINT NOT NULL,
    menu_item_id BIGINT NOT NULL,
    server_menu_item_id BIGINT,
    variant_id BIGINT,
    server_variant_id BIGINT,
    delta NUMERIC(12,4) NOT NULL,
    reason VARCHAR(255) NOT NULL
);

CREATE INDEX IF NOT EXISTS idx_stock_logs_tenant_updated ON stock_logs(restaurant_id, updated_at);
CREATE INDEX IF NOT EXISTS idx_stock_logs_device ON stock_logs(restaurant_id, device_id, local_id);

CREATE TABLE IF NOT EXISTS menu_extraction_jobs (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    restaurant_id BIGINT,
    file_path VARCHAR(500),
    status VARCHAR(50),
    extracted_data_json TEXT,
    created_at TIMESTAMP,
    completed_at TIMESTAMP,
    error_message TEXT
);
