-- Multi-device invoice identity (PLAN §4.2–§4.4).
--
-- Adds the structured invoice-numbering columns the Bill entity now declares,
-- creates the server-owned terminal registration table used to gate invoice
-- allocation, makes the legacy lifetime_order_id nullable (Option A), and drops
-- the V22 guarded lifetime/daily uniqueness indexes in favour of series-aware
-- uniqueness.
--
-- DEV-SAFE scope: this migration is idempotent and safe on a fresh or dev
-- database. It does NOT reconcile pre-existing duplicate printed invoice
-- numbers on a production database; that audit is handled separately per
-- PLAN §4.4 / §10. The new invoice-uniqueness index is therefore created behind
-- a duplicate guard (same pattern as V22) so an unclean DB is not blocked.

-- 1. New numbering columns on bills (types match Bill.java for ddl-auto=validate).
ALTER TABLE bills ADD COLUMN IF NOT EXISTS terminal_series   VARCHAR(255);
ALTER TABLE bills ADD COLUMN IF NOT EXISTS financial_year    VARCHAR(255);
ALTER TABLE bills ADD COLUMN IF NOT EXISTS invoice_series    VARCHAR(255);
ALTER TABLE bills ADD COLUMN IF NOT EXISTS invoice_sequence  BIGINT;
ALTER TABLE bills ADD COLUMN IF NOT EXISTS invoice_number    VARCHAR(255);

-- 2. lifetime_order_id becomes nullable and legacy-only (PLAN §4.3, Option A).
ALTER TABLE bills ALTER COLUMN lifetime_order_id DROP NOT NULL;

-- 3. Ensure every bill has a canonical public_token before relying on it (PLAN §4.1).
UPDATE bills SET public_token = gen_random_uuid() WHERE public_token IS NULL;

DO $$
BEGIN
    IF NOT EXISTS (
        SELECT 1
        FROM bills
        GROUP BY public_token
        HAVING COUNT(*) > 1
    ) THEN
        CREATE UNIQUE INDEX IF NOT EXISTS ux_bills_public_token
            ON bills (public_token);
        DROP INDEX IF EXISTS idx_bills_public_token;
    ELSE
        RAISE NOTICE 'Skipping ux_bills_public_token: duplicate public tokens require manual reconciliation.';
    END IF;
END $$;

-- 4. Server-owned terminal registration (PLAN §5). Matches RestaurantTerminal.
CREATE TABLE IF NOT EXISTS restaurant_terminal (
    id              BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    restaurant_id   BIGINT       NOT NULL,
    terminal_series VARCHAR(255) NOT NULL,
    device_id       VARCHAR(255),
    created_at      BIGINT,
    updated_at      BIGINT
);

CREATE UNIQUE INDEX IF NOT EXISTS ux_restaurant_terminal_series
    ON restaurant_terminal (restaurant_id, terminal_series);
CREATE UNIQUE INDEX IF NOT EXISTS ux_restaurant_terminal_device
    ON restaurant_terminal (restaurant_id, device_id)
    WHERE device_id IS NOT NULL;
CREATE INDEX IF NOT EXISTS idx_restaurant_terminal_restaurant
    ON restaurant_terminal (restaurant_id);

-- 5. Drop the V22 guarded lifetime/daily uniqueness indexes (PLAN §4.4 steps 8–9).
--    These couple a display counter to bill identity and are replaced below.
DROP INDEX IF EXISTS ux_bills_restaurant_lifetime_order_active;
DROP INDEX IF EXISTS ux_bills_restaurant_daily_order_active;

-- 6. Series-aware invoice uniqueness, created only when no active duplicates
--    already exist (dev-safe guard; production duplicate reconciliation is a
--    separate accounting task per PLAN §4.4 / §10).
DO $$
BEGIN
    IF NOT EXISTS (
        SELECT 1
        FROM bills
        WHERE is_deleted = false
          AND invoice_number IS NOT NULL
        GROUP BY restaurant_id, financial_year, invoice_series, invoice_sequence
        HAVING COUNT(*) > 1
    ) THEN
        CREATE UNIQUE INDEX IF NOT EXISTS ux_bills_restaurant_invoice_series_active
            ON bills (restaurant_id, financial_year, invoice_series, invoice_sequence)
            WHERE is_deleted = false AND invoice_number IS NOT NULL;
    ELSE
        RAISE NOTICE 'Skipping ux_bills_restaurant_invoice_series_active: duplicate active invoice sequences exist and require manual reconciliation.';
    END IF;
END $$;

-- 7. Series-aware order (daily) uniqueness per terminal, same guard.
DO $$
BEGIN
    IF NOT EXISTS (
        SELECT 1
        FROM bills
        WHERE is_deleted = false
          AND last_reset_date IS NOT NULL
          AND daily_order_id IS NOT NULL
        GROUP BY restaurant_id, last_reset_date, terminal_series, daily_order_id
        HAVING COUNT(*) > 1
    ) THEN
        CREATE UNIQUE INDEX IF NOT EXISTS ux_bills_restaurant_terminal_daily_active
            ON bills (restaurant_id, last_reset_date, terminal_series, daily_order_id)
            WHERE is_deleted = false;
    ELSE
        RAISE NOTICE 'Skipping ux_bills_restaurant_terminal_daily_active: duplicate active daily order numbers exist and require manual reconciliation.';
    END IF;
END $$;
