CREATE TABLE chargebacks (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    restaurant_id BIGINT NOT NULL,
    bill_id BIGINT,
    easebuzz_txn_id VARCHAR(64),
    amount NUMERIC(12,2) NOT NULL,
    reason_code VARCHAR(64),
    reason_description TEXT,
    status VARCHAR(32) NOT NULL DEFAULT 'OPEN',
    fraud_score NUMERIC(5,2),
    evidence_url VARCHAR(512),
    customer_name VARCHAR(255),
    customer_phone VARCHAR(32),
    created_at BIGINT NOT NULL,
    resolved_at BIGINT
);

CREATE INDEX idx_chargebacks_restaurant ON chargebacks(restaurant_id);
CREATE INDEX idx_chargebacks_status ON chargebacks(status);
CREATE INDEX idx_chargebacks_bill ON chargebacks(bill_id);
