CREATE TABLE customer_profiles (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    restaurant_id BIGINT NOT NULL,
    phone_hash VARCHAR(64) NOT NULL,
    display_name VARCHAR(255),
    total_orders BIGINT NOT NULL DEFAULT 0,
    total_spend NUMERIC(12,2) NOT NULL DEFAULT 0,
    average_order_value NUMERIC(12,2),
    last_order_at BIGINT,
    first_order_at BIGINT,
    preferred_payment_mode VARCHAR(32),
    segment VARCHAR(32),
    created_at BIGINT NOT NULL,
    updated_at BIGINT NOT NULL
);

CREATE INDEX idx_customer_restaurant ON customer_profiles(restaurant_id);
CREATE INDEX idx_customer_phone_hash ON customer_profiles(phone_hash);
CREATE UNIQUE INDEX uk_customer_restaurant_phone ON customer_profiles(restaurant_id, phone_hash);
