/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ProtoSystemRouteImport } from './routes/proto.system'
import { Route as ProtoLoginRouteImport } from './routes/proto.login'
import { Route as ProtoForgotRouteImport } from './routes/proto.forgot'
import { Route as ProtoShopTerminalsRouteImport } from './routes/proto.shop.terminals'
import { Route as ProtoOwnerTerminalsRouteImport } from './routes/proto.owner.terminals'
import { Route as ProtoOwnerStaffRouteImport } from './routes/proto.owner.staff'
import { Route as ProtoOwnerReportsRouteImport } from './routes/proto.owner.reports'
import { Route as ProtoOwnerOrdersRouteImport } from './routes/proto.owner.orders'
import { Route as ProtoOwnerMenuRouteImport } from './routes/proto.owner.menu'
import { Route as ProtoOwnerMarketplaceRouteImport } from './routes/proto.owner.marketplace'
import { Route as ProtoOwnerDashboardRouteImport } from './routes/proto.owner.dashboard'
import { Route as ProtoAdminDashboardRouteImport } from './routes/proto.admin.dashboard'
import { Route as ProtoAdminBusinessesRouteImport } from './routes/proto.admin.businesses'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ProtoSystemRoute = ProtoSystemRouteImport.update({
  id: '/proto/system',
  path: '/proto/system',
  getParentRoute: () => rootRouteImport,
} as any)
const ProtoLoginRoute = ProtoLoginRouteImport.update({
  id: '/proto/login',
  path: '/proto/login',
  getParentRoute: () => rootRouteImport,
} as any)
const ProtoForgotRoute = ProtoForgotRouteImport.update({
  id: '/proto/forgot',
  path: '/proto/forgot',
  getParentRoute: () => rootRouteImport,
} as any)
const ProtoShopTerminalsRoute = ProtoShopTerminalsRouteImport.update({
  id: '/proto/shop/terminals',
  path: '/proto/shop/terminals',
  getParentRoute: () => rootRouteImport,
} as any)
const ProtoOwnerTerminalsRoute = ProtoOwnerTerminalsRouteImport.update({
  id: '/proto/owner/terminals',
  path: '/proto/owner/terminals',
  getParentRoute: () => rootRouteImport,
} as any)
const ProtoOwnerStaffRoute = ProtoOwnerStaffRouteImport.update({
  id: '/proto/owner/staff',
  path: '/proto/owner/staff',
  getParentRoute: () => rootRouteImport,
} as any)
const ProtoOwnerReportsRoute = ProtoOwnerReportsRouteImport.update({
  id: '/proto/owner/reports',
  path: '/proto/owner/reports',
  getParentRoute: () => rootRouteImport,
} as any)
const ProtoOwnerOrdersRoute = ProtoOwnerOrdersRouteImport.update({
  id: '/proto/owner/orders',
  path: '/proto/owner/orders',
  getParentRoute: () => rootRouteImport,
} as any)
const ProtoOwnerMenuRoute = ProtoOwnerMenuRouteImport.update({
  id: '/proto/owner/menu',
  path: '/proto/owner/menu',
  getParentRoute: () => rootRouteImport,
} as any)
const ProtoOwnerMarketplaceRoute = ProtoOwnerMarketplaceRouteImport.update({
  id: '/proto/owner/marketplace',
  path: '/proto/owner/marketplace',
  getParentRoute: () => rootRouteImport,
} as any)
const ProtoOwnerDashboardRoute = ProtoOwnerDashboardRouteImport.update({
  id: '/proto/owner/dashboard',
  path: '/proto/owner/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const ProtoAdminDashboardRoute = ProtoAdminDashboardRouteImport.update({
  id: '/proto/admin/dashboard',
  path: '/proto/admin/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const ProtoAdminBusinessesRoute = ProtoAdminBusinessesRouteImport.update({
  id: '/proto/admin/businesses',
  path: '/proto/admin/businesses',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/proto/forgot': typeof ProtoForgotRoute
  '/proto/login': typeof ProtoLoginRoute
  '/proto/system': typeof ProtoSystemRoute
  '/proto/admin/businesses': typeof ProtoAdminBusinessesRoute
  '/proto/admin/dashboard': typeof ProtoAdminDashboardRoute
  '/proto/owner/dashboard': typeof ProtoOwnerDashboardRoute
  '/proto/owner/marketplace': typeof ProtoOwnerMarketplaceRoute
  '/proto/owner/menu': typeof ProtoOwnerMenuRoute
  '/proto/owner/orders': typeof ProtoOwnerOrdersRoute
  '/proto/owner/reports': typeof ProtoOwnerReportsRoute
  '/proto/owner/staff': typeof ProtoOwnerStaffRoute
  '/proto/owner/terminals': typeof ProtoOwnerTerminalsRoute
  '/proto/shop/terminals': typeof ProtoShopTerminalsRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/proto/forgot': typeof ProtoForgotRoute
  '/proto/login': typeof ProtoLoginRoute
  '/proto/system': typeof ProtoSystemRoute
  '/proto/admin/businesses': typeof ProtoAdminBusinessesRoute
  '/proto/admin/dashboard': typeof ProtoAdminDashboardRoute
  '/proto/owner/dashboard': typeof ProtoOwnerDashboardRoute
  '/proto/owner/marketplace': typeof ProtoOwnerMarketplaceRoute
  '/proto/owner/menu': typeof ProtoOwnerMenuRoute
  '/proto/owner/orders': typeof ProtoOwnerOrdersRoute
  '/proto/owner/reports': typeof ProtoOwnerReportsRoute
  '/proto/owner/staff': typeof ProtoOwnerStaffRoute
  '/proto/owner/terminals': typeof ProtoOwnerTerminalsRoute
  '/proto/shop/terminals': typeof ProtoShopTerminalsRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/proto/forgot': typeof ProtoForgotRoute
  '/proto/login': typeof ProtoLoginRoute
  '/proto/system': typeof ProtoSystemRoute
  '/proto/admin/businesses': typeof ProtoAdminBusinessesRoute
  '/proto/admin/dashboard': typeof ProtoAdminDashboardRoute
  '/proto/owner/dashboard': typeof ProtoOwnerDashboardRoute
  '/proto/owner/marketplace': typeof ProtoOwnerMarketplaceRoute
  '/proto/owner/menu': typeof ProtoOwnerMenuRoute
  '/proto/owner/orders': typeof ProtoOwnerOrdersRoute
  '/proto/owner/reports': typeof ProtoOwnerReportsRoute
  '/proto/owner/staff': typeof ProtoOwnerStaffRoute
  '/proto/owner/terminals': typeof ProtoOwnerTerminalsRoute
  '/proto/shop/terminals': typeof ProtoShopTerminalsRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/proto/forgot'
    | '/proto/login'
    | '/proto/system'
    | '/proto/admin/businesses'
    | '/proto/admin/dashboard'
    | '/proto/owner/dashboard'
    | '/proto/owner/marketplace'
    | '/proto/owner/menu'
    | '/proto/owner/orders'
    | '/proto/owner/reports'
    | '/proto/owner/staff'
    | '/proto/owner/terminals'
    | '/proto/shop/terminals'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/proto/forgot'
    | '/proto/login'
    | '/proto/system'
    | '/proto/admin/businesses'
    | '/proto/admin/dashboard'
    | '/proto/owner/dashboard'
    | '/proto/owner/marketplace'
    | '/proto/owner/menu'
    | '/proto/owner/orders'
    | '/proto/owner/reports'
    | '/proto/owner/staff'
    | '/proto/owner/terminals'
    | '/proto/shop/terminals'
  id:
    | '__root__'
    | '/'
    | '/proto/forgot'
    | '/proto/login'
    | '/proto/system'
    | '/proto/admin/businesses'
    | '/proto/admin/dashboard'
    | '/proto/owner/dashboard'
    | '/proto/owner/marketplace'
    | '/proto/owner/menu'
    | '/proto/owner/orders'
    | '/proto/owner/reports'
    | '/proto/owner/staff'
    | '/proto/owner/terminals'
    | '/proto/shop/terminals'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ProtoForgotRoute: typeof ProtoForgotRoute
  ProtoLoginRoute: typeof ProtoLoginRoute
  ProtoSystemRoute: typeof ProtoSystemRoute
  ProtoAdminBusinessesRoute: typeof ProtoAdminBusinessesRoute
  ProtoAdminDashboardRoute: typeof ProtoAdminDashboardRoute
  ProtoOwnerDashboardRoute: typeof ProtoOwnerDashboardRoute
  ProtoOwnerMarketplaceRoute: typeof ProtoOwnerMarketplaceRoute
  ProtoOwnerMenuRoute: typeof ProtoOwnerMenuRoute
  ProtoOwnerOrdersRoute: typeof ProtoOwnerOrdersRoute
  ProtoOwnerReportsRoute: typeof ProtoOwnerReportsRoute
  ProtoOwnerStaffRoute: typeof ProtoOwnerStaffRoute
  ProtoOwnerTerminalsRoute: typeof ProtoOwnerTerminalsRoute
  ProtoShopTerminalsRoute: typeof ProtoShopTerminalsRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/proto/system': {
      id: '/proto/system'
      path: '/proto/system'
      fullPath: '/proto/system'
      preLoaderRoute: typeof ProtoSystemRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/proto/login': {
      id: '/proto/login'
      path: '/proto/login'
      fullPath: '/proto/login'
      preLoaderRoute: typeof ProtoLoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/proto/forgot': {
      id: '/proto/forgot'
      path: '/proto/forgot'
      fullPath: '/proto/forgot'
      preLoaderRoute: typeof ProtoForgotRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/proto/shop/terminals': {
      id: '/proto/shop/terminals'
      path: '/proto/shop/terminals'
      fullPath: '/proto/shop/terminals'
      preLoaderRoute: typeof ProtoShopTerminalsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/proto/owner/terminals': {
      id: '/proto/owner/terminals'
      path: '/proto/owner/terminals'
      fullPath: '/proto/owner/terminals'
      preLoaderRoute: typeof ProtoOwnerTerminalsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/proto/owner/staff': {
      id: '/proto/owner/staff'
      path: '/proto/owner/staff'
      fullPath: '/proto/owner/staff'
      preLoaderRoute: typeof ProtoOwnerStaffRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/proto/owner/reports': {
      id: '/proto/owner/reports'
      path: '/proto/owner/reports'
      fullPath: '/proto/owner/reports'
      preLoaderRoute: typeof ProtoOwnerReportsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/proto/owner/orders': {
      id: '/proto/owner/orders'
      path: '/proto/owner/orders'
      fullPath: '/proto/owner/orders'
      preLoaderRoute: typeof ProtoOwnerOrdersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/proto/owner/menu': {
      id: '/proto/owner/menu'
      path: '/proto/owner/menu'
      fullPath: '/proto/owner/menu'
      preLoaderRoute: typeof ProtoOwnerMenuRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/proto/owner/marketplace': {
      id: '/proto/owner/marketplace'
      path: '/proto/owner/marketplace'
      fullPath: '/proto/owner/marketplace'
      preLoaderRoute: typeof ProtoOwnerMarketplaceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/proto/owner/dashboard': {
      id: '/proto/owner/dashboard'
      path: '/proto/owner/dashboard'
      fullPath: '/proto/owner/dashboard'
      preLoaderRoute: typeof ProtoOwnerDashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/proto/admin/dashboard': {
      id: '/proto/admin/dashboard'
      path: '/proto/admin/dashboard'
      fullPath: '/proto/admin/dashboard'
      preLoaderRoute: typeof ProtoAdminDashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/proto/admin/businesses': {
      id: '/proto/admin/businesses'
      path: '/proto/admin/businesses'
      fullPath: '/proto/admin/businesses'
      preLoaderRoute: typeof ProtoAdminBusinessesRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ProtoForgotRoute: ProtoForgotRoute,
  ProtoLoginRoute: ProtoLoginRoute,
  ProtoSystemRoute: ProtoSystemRoute,
  ProtoAdminBusinessesRoute: ProtoAdminBusinessesRoute,
  ProtoAdminDashboardRoute: ProtoAdminDashboardRoute,
  ProtoOwnerDashboardRoute: ProtoOwnerDashboardRoute,
  ProtoOwnerMarketplaceRoute: ProtoOwnerMarketplaceRoute,
  ProtoOwnerMenuRoute: ProtoOwnerMenuRoute,
  ProtoOwnerOrdersRoute: ProtoOwnerOrdersRoute,
  ProtoOwnerReportsRoute: ProtoOwnerReportsRoute,
  ProtoOwnerStaffRoute: ProtoOwnerStaffRoute,
  ProtoOwnerTerminalsRoute: ProtoOwnerTerminalsRoute,
  ProtoShopTerminalsRoute: ProtoShopTerminalsRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
