package com.khanabook.lite.pos.domain.manager

import android.content.Context
import android.graphics.Canvas
import android.graphics.Color
import android.graphics.Paint
import android.graphics.pdf.PdfDocument
import com.khanabook.lite.pos.domain.model.OrderDetailRow
import com.khanabook.lite.pos.domain.util.DateUtils
import java.io.File
import java.io.FileOutputStream

class ReportExporter(private val context: Context) {

    private val pageWidth = 595
    private val pageHeight = 842
    private val margin = 40f

    fun exportToPdf(
        reportType: String,
        timeFilter: String,
        paymentBreakdown: Map<String, String>,
        orderRows: List<OrderDetailRow>,
        shopName: String?
    ): File {
        val document = PdfDocument()
        var pageNumber = 1
        var pageInfo = PdfDocument.PageInfo.Builder(pageWidth, pageHeight, pageNumber).create()
        var page = document.startPage(pageInfo)
        var canvas = page.canvas
        var y = margin

        val titlePaint = Paint().apply { textSize = 16f; isFakeBoldText = true; color = Color.BLACK }
        val subPaint = Paint().apply { textSize = 11f; color = Color.DKGRAY }
        val headerPaint = Paint().apply { textSize = 10f; isFakeBoldText = true; color = Color.BLACK }
        val cellPaint = Paint().apply { textSize = 10f; color = Color.BLACK }
        val linePaint = Paint().apply { strokeWidth = 0.5f; color = Color.LTGRAY }

        fun newPage() {
            document.finishPage(page)
            pageNumber++
            pageInfo = PdfDocument.PageInfo.Builder(pageWidth, pageHeight, pageNumber).create()
            page = document.startPage(pageInfo)
            canvas = page.canvas
            y = margin
        }

        fun checkOverflow() { if (y > pageHeight - margin) newPage() }

        // Title
        shopName?.takeIf { it.isNotBlank() }?.let {
            canvas.drawText(it, margin, y, titlePaint); y += 22f
        }
        canvas.drawText("$reportType Level Report — $timeFilter", margin, y, titlePaint); y += 18f
        canvas.drawLine(margin, y, pageWidth - margin, y, linePaint); y += 14f

        if (reportType == "Payment") {
            // Header
            canvas.drawText("Payment Mode", margin, y, headerPaint)
            canvas.drawText("Amount (Rs.)", margin + 300f, y, headerPaint)
            y += 12f
            canvas.drawLine(margin, y, pageWidth - margin, y, linePaint); y += 12f

            paymentBreakdown.forEach { (mode, amount) ->
                if (!mode.contains("_part")) {
                    checkOverflow()
                    canvas.drawText(mode, margin, y, cellPaint)
                    canvas.drawText(amount, margin + 300f, y, cellPaint)
                    y += 16f
                }
            }
        } else {
            // Columns: Order#, Invoice, Mode, Status, Amount, Date
            val cols = listOf(margin, margin + 60f, margin + 140f, margin + 220f, margin + 310f, margin + 400f)
            canvas.drawText("Order#", cols[0], y, headerPaint)
            canvas.drawText("Invoice", cols[1], y, headerPaint)
            canvas.drawText("Mode", cols[2], y, headerPaint)
            canvas.drawText("Status", cols[3], y, headerPaint)
            canvas.drawText("Amount", cols[4], y, headerPaint)
            canvas.drawText("Date", cols[5], y, headerPaint)
            y += 12f
            canvas.drawLine(margin, y, pageWidth - margin, y, linePaint); y += 12f

            orderRows.forEach { row ->
                checkOverflow()
                val status = row.orderStatus.name.lowercase().replaceFirstChar { it.uppercase() }
                val date = DateUtils.formatDisplayDate(row.salesDate)
                canvas.drawText(row.dailyNo, cols[0], y, cellPaint)
                canvas.drawText("INV${row.lifetimeNo}", cols[1], y, cellPaint)
                canvas.drawText(row.payMode.displayLabel.take(10), cols[2], y, cellPaint)
                canvas.drawText(status.take(10), cols[3], y, cellPaint)
                canvas.drawText(row.salesAmount, cols[4], y, cellPaint)
                canvas.drawText(date.take(10), cols[5], y, cellPaint)
                y += 16f
            }
        }

        y += 10f
        checkOverflow()
        canvas.drawLine(margin, y, pageWidth - margin, y, linePaint); y += 12f
        canvas.drawText("Generated by KhanaBook", margin, y, subPaint)

        document.finishPage(page)
        val file = File(context.cacheDir, "KhanaBook_${reportType}_${timeFilter}.pdf")
        FileOutputStream(file).use { document.writeTo(it) }
        document.close()
        return file
    }

    fun exportToCsv(
        reportType: String,
        timeFilter: String,
        paymentBreakdown: Map<String, String>,
        orderRows: List<OrderDetailRow>,
        shopName: String?
    ): File {
        val sb = StringBuilder()
        shopName?.takeIf { it.isNotBlank() }?.let { sb.appendLine(it) }
        sb.appendLine("$reportType Level Report - $timeFilter")
        sb.appendLine()

        if (reportType == "Payment") {
            sb.appendLine("Payment Mode,Amount (Rs.)")
            paymentBreakdown.forEach { (mode, amount) ->
                if (!mode.contains("_part")) sb.appendLine("$mode,$amount")
            }
        } else {
            sb.appendLine("Order No,Invoice No,Payment Mode,Status,Amount (Rs.),Date")
            orderRows.forEach { row ->
                val status = row.orderStatus.name.lowercase().replaceFirstChar { it.uppercase() }
                val date = DateUtils.formatDisplayDate(row.salesDate)
                sb.appendLine("${row.dailyNo},INV${row.lifetimeNo},${row.payMode.displayLabel},$status,${row.salesAmount},$date")
            }
        }

        sb.appendLine()
        sb.appendLine("Generated by KhanaBook")
        val file = File(context.cacheDir, "KhanaBook_${reportType}_${timeFilter}.csv")
        file.writeText(sb.toString())
        return file
    }
}
